apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strava

resources:
  - namespace.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - secret.enc.yaml
  - ingress.yaml
  - middleware.yaml
  - strava-webhook.yaml
